Drop database if exists pokedex;
CREATE DATABASE pokedex;
USE pokedex;

CREATE TABLE pokemon
(
    id   INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255)
);

ALTER TABLE pokemon
    ADD caught BOOLEAN DEFAULT FALSE,
    ADD type  ENUM (
        'Grass', 'Fire', 'Water', 'Bug', 'Normal',
        'Poison', 'Electric', 'Ground', 'Fairy',
        'Fighting', 'Psychic', 'Rock', 'Ghost') NOT NULL;

INSERT INTO pokemon (name, type, caught)
VALUES ('Bulbasaur', 'Grass', 0),
       ('Ivysaur', 'Grass', 0),
       ('Venusaur', 'Grass', 0),
       ('Charmander', 'Fire', 0),
       ('Charmeleon', 'Fire', 0),
       ('Charizard', 'Fire', 0),
       ('Squirtle', 'Water', 0),
       ('Wartortle', 'Water', 0),
       ('Blastoise', 'Water', 0),
       ('Caterpie', 'Bug', 0),
       ('Metapod', 'Bug', 0),
       ('Butterfree', 'Bug', 0),
       ('Weedle', 'Bug', 0),
       ('Kakuna', 'Bug', 0),
       ('Beedrill', 'Bug', 0),
       ('Pidgey', 'Normal', 0),
       ('Pidgeotto', 'Normal', 0),
       ('Pidgeot', 'Normal', 0),
       ('Rattata', 'Normal', 0),
       ('Raticate', 'Normal', 0),
       ('Spearow', 'Normal', 0),
       ('Fearow', 'Normal', 0),
       ('Ekans', 'Poison', 0),
       ('Arbok', 'Poison', 0),
       ('Pikachu', 'Electric', 0),
       ('Raichu', 'Electric', 0),
       ('Sandshrew', 'Ground', 0),
       ('Sandslash', 'Ground', 0),
       ('Nidoran♀', 'Poison', 0),
       ('Nidorina', 'Poison', 0),
       ('Nidoqueen', 'Poison', 0),
       ('Nidoran♂', 'Poison', 0),
       ('Nidorino', 'Poison', 0),
       ('Nidoking', 'Poison', 0),
       ('Clefairy', 'Fairy', 0),
       ('Clefable', 'Fairy', 0),
       ('Vulpix', 'Fire', 0),
       ('Ninetales', 'Fire', 0),
       ('Jigglypuff', 'Normal', 0),
       ('Wigglytuff', 'Normal', 0),
       ('Zubat', 'Poison', 0),
       ('Golbat', 'Poison', 0),
       ('Oddish', 'Grass', 0),
       ('Gloom', 'Grass', 0),
       ('Vileplume', 'Grass', 0),
       ('Paras', 'Bug', 0),
       ('Parasect', 'Bug', 0),
       ('Venonat', 'Bug', 0),
       ('Venomoth', 'Bug', 0),
       ('Diglett', 'Ground', 0),
       ('Dugtrio', 'Ground', 0),
       ('Meowth', 'Normal', 0),
       ('Persian', 'Normal', 0),
       ('Psyduck', 'Water', 0),
       ('Golduck', 'Water', 0),
       ('Mankey', 'Fighting', 0),
       ('Primeape', 'Fighting', 0),
       ('Growlithe', 'Fire', 0),
       ('Arcanine', 'Fire', 0),
       ('Poliwag', 'Water', 0),
       ('Poliwhirl', 'Water', 0),
       ('Poliwrath', 'Water', 0),
       ('Abra', 'Psychic', 0),
       ('Kadabra', 'Psychic', 0),
       ('Alakazam', 'Psychic', 0),
       ('Machop', 'Fighting', 0),
       ('Machoke', 'Fighting', 0),
       ('Machamp', 'Fighting', 0),
       ('Bellsprout', 'Grass', 0),
       ('Weepinbell', 'Grass', 0),
       ('Victreebel', 'Grass', 0),
       ('Tentacool', 'Water', 0),
       ('Tentacruel', 'Water', 0),
       ('Geodude', 'Rock', 0),
       ('Graveler', 'Rock', 0),
       ('Golem', 'Rock', 0),
       ('Ponyta', 'Fire', 0),
       ('Rapidash', 'Fire', 0),
       ('Slowpoke', 'Water', 0),
       ('Slowbro', 'Water', 0),
       ('Magnemite', 'Electric', 0),
       ('Magneton', 'Electric', 0),
       ('Farfetch\'d', 'Normal', 0),
       ('Doduo', 'Normal', 0),
       ('Dodrio', 'Normal', 0),
       ('Seel', 'Water', 0),
       ('Dewgong', 'Water', 0),
       ('Grimer', 'Poison', 0),
       ('Muk', 'Poison', 0),
       ('Shellder', 'Water', 0),
       ('Cloyster', 'Water', 0),
       ('Gastly', 'Ghost', 0),
       ('Haunter', 'Ghost', 0),
       ('Gengar', 'Ghost', 0),
       ('Onix', 'Rock', 0),
       ('Drowzee', 'Psychic', 0),
       ('Hypno', 'Psychic', 0),
       ('Krabby', 'Water', 0),
       ('Kingler', 'Water', 0);

